### ISSUE TITLE
Having trouble generation_script.py

### ISSUE THREAD

**Issue by whikwon** [ctallec/world-models#2]
![image](https://user-images.githubusercontent.com/30768596/42080742-9c2beb14-7bbe-11e8-9719-9156c6d098a8.png)

I'm having this error while executing generation_script.py 

Could you help resolving this error? 

I ran in python=3.5, 3.6, pytorch=4.0, cuda=9.0, cudnn=7 and `pip install -r requirements.txt`

**Comment by whikwon** [comment]
Thank you I'll try it out.

**Comment by twoflypig** [comment]
Hi,I just had the same error as you have . For my  case , I use anaconda2  and I am on Ubuntu 18.04 .
And I run this command on shell
`glxinfo`
got the followings:
```
name of display: :1
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  53
  Current serial number in output stream:  52
```
The problem is that in my  anaconda environment (i.e /home/me/anaconda2/envs/tensorflow-gpu/lib),the file libstdc++.so **is not** assosciated with  system's drivers( I 'm not totally sure about this). So we can do followings.

```
cd /home/me/anaconda2/envs/tensorflow-gpu/lib (cd the environment where you excute the command)
mkdir backup  #backup the origin libstdc++
mv libstd* backup  
#copy  the system's libstdc++.so.6 to the local folder
cp /usr/lib/x86_64-linux-gnu/libstdc++.so.6  ./
# create soft links
ln -s libstdc++.so.6 libstdc++.so
ln -s libstdc++.so.6 libstdc++.so.6.0.19
 
```
Then excute `glxinfo` anagin on shell you will get 
```
name of display: :1
display: :1  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
server glx extensions:
....
```
Finally , it works when I excute the  generation_script.py . 
ref: [csdn bolg in chinese](https://blog.csdn.net/acsunqi/article/details/78231336)

**Comment by whikwon** [comment]
I'm not executing in the server and when i execute your command, 
`Traceback (most recent call last):
    File "generation_script.py", line 20, in <module>
    rpt = args.roolouts // args.threads + 1
TypeError: unsupported operand type(s) for //: 'NoneType' and 'NoneType'`

**Comment by Diviyan-Kalainathan** [comment]
I forgot to add the command line arguments in my previous comment: 
```bash
xvfb-run -s "-screen 0 600x400x24" python data/generation_script.py --rollouts 1000 --rootdir datasets/carracing --threads 8
```

**Comment by sg2** [comment]
I am getting a similar error. I am running within a conda environment that I created for this project. I am running locally (not over a server) and I can pass all the OpenAI gym unit tests (I install gym from source, and within the the gym git directory, with my conda environment activated, run 'python -m test'). I then run the following command

`PYTHONPATH='.' python data/generation_script.py --rollouts 1000 --rootdir datasets/carracing --threads 1`

(See this Issue for PYTHONPATH addition to command: [https://github.com/ctallec/world-models/issues/20](https://github.com/ctallec/world-models/issues/20))

Calling `generation_script.py` fails with the following:

```
xvfb-run -s "-screen 0 1400x900x24" --server-num=1 python data/carracing.py --dir datasets/carracing/thread_0 --rollouts 1001 --policy brown
Track generation: 1063..1333 -> 270-tiles track
Traceback (most recent call last):
  File "data/carracing.py", line 58, in <module>
    generate_data(args.rollouts, args.dir, args.policy)
  File "data/carracing.py", line 20, in generate_data
    env.reset()
  File "/media/storage/world-models/gym/gym/wrappers/time_limit.py", line 44, in reset
    return self.env.reset(**kwargs)
  File "/media/storage/world-models/gym/gym/envs/box2d/car_racing.py", line 293, in reset
    return self.step(None)[0]
  File "/media/storage/world-models/gym/gym/envs/box2d/car_racing.py", line 305, in step
    self.state = self.render("state_pixels")
  File "/media/storage/world-models/gym/gym/envs/box2d/car_racing.py", line 327, in render
    from gym.envs.classic_control import rendering
  File "/media/storage/world-models/gym/gym/envs/classic_control/rendering.py", line 23, in <module>
    from pyglet.gl import *
  File "/home/sam/anaconda3/envs/ctallec-world-models/lib/python3.7/site-packages/pyglet/gl/__init__.py", line 239, in <module>
    import pyglet.window
  File "/home/sam/anaconda3/envs/ctallec-world-models/lib/python3.7/site-packages/pyglet/window/__init__.py", line 1896, in <module>
    gl._create_shadow_window()
  File "/home/sam/anaconda3/envs/ctallec-world-models/lib/python3.7/site-packages/pyglet/gl/__init__.py", line 208, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/sam/anaconda3/envs/ctallec-world-models/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py", line 166, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/sam/anaconda3/envs/ctallec-world-models/lib/python3.7/site-packages/pyglet/window/__init__.py", line 571, in __init__
    self._create()
  File "/home/sam/anaconda3/envs/ctallec-world-models/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py", line 263, in _create
    self.context.attach(self.canvas)
  File "/home/sam/anaconda3/envs/ctallec-world-models/lib/python3.7/site-packages/pyglet/gl/xlib.py", line 323, in attach
    self.set_current()
  File "/home/sam/anaconda3/envs/ctallec-world-models/lib/python3.7/site-packages/pyglet/gl/xlib.py", line 328, in set_current
    super(XlibContext13, self).set_current()
  File "/home/sam/anaconda3/envs/ctallec-world-models/lib/python3.7/site-packages/pyglet/gl/base.py", line 301, in set_current
    gl_info.set_active_context()
  File "/home/sam/anaconda3/envs/ctallec-world-models/lib/python3.7/site-packages/pyglet/gl/gl_info.py", line 98, in set_active_context
    if self.have_version(3):
  File "/home/sam/anaconda3/envs/ctallec-world-models/lib/python3.7/site-packages/pyglet/gl/gl_info.py", line 170, in have_version
    imajor, iminor, irelease = [int(v) for v in ver.split('.', 3)[:3]]
  File "/home/sam/anaconda3/envs/ctallec-world-models/lib/python3.7/site-packages/pyglet/gl/gl_info.py", line 170, in <listcomp>
    imajor, iminor, irelease = [int(v) for v in ver.split('.', 3)[:3]]
ValueError: invalid literal for int() with base 10: ''
```
Do I need to make a different call to `xvfb-run`?

**Comment by waiyc** [comment]
@sg2 I am facing the same issue. I disable the following lines to disable `xvfb-run` in generation_script.py and it start to generate random rollout data.
>#cmd = ['xvfb-run', '-s', '"-screen 0 1400x900x24"']
#cmd += ['--server-num={}'.format(i + 1)]
cmd = ["python", "-m", "data.carracing", "--dir",
tdir, "--rollouts", str(rpt), "--policy", args.policy]

Hope it helps :)

**Comment by philipjball** [comment]
I was having exactly the same error, and my `glxinfo` and `xvfb-run` were working as expected. Instead it seems to have been a build issue with `Box2D`. I believe that this happens because for some reason not having a display (I'm sshing into a VM) makes the `Box2D-py` in `gym` not work properly, so you must roll it back to an older version (`2.3.2/2.3.3`). This older version however will only work if you build it with a specific version of `swig`. So in short, I had to do the following:
* Upgrade Ubuntu from 16.04 -> 18.04 (so I can use `swig 3.0.12`)
* Install the requirements as stated, except just `gym` (not `gym[all]`)
* Downgrade `pyglet` to `1.3.2`
* Install `box2d` **and** `box2d-kengz`

**Comment by giubacchio** [comment]
I still have the same error. 
I'm using conda, and I followed the suggestions given by @fiorenza2, apart from upgrading to Ubuntu 18.04 (I managed to install _swig 3.0.12_, _box2d 2.3.2_, and _box2d-kengz_, the last two using _pip_).
It gives me the same error both locally and sshing to a server, in both cases using _xvfb-run_. 

However, it works locally if I don't use _xvfb_, so I suspect that _xvfb_ may be the cause. Unluckily, the same error appears when training the controller, and in this case I can't do it locally because the GPUs are in the server.

Any other suggestion? 

Thank you

**Comment by 0xsamgreen** [comment]
@giubacchio can you provide a requirements.txt file for your installation? If you can, I'll see if I can run it.

**Comment by giubacchio** [comment]
@sg2 Here is the list with the commands I used to set the conda environment, together with the last rows of the error I get.
[conda_installation_and_error.txt](https://github.com/ctallec/world-models/files/3830576/conda_installation_and_error.txt)
